
---
services:
    laravel.test:
        build: .
        depends_on:
            - db
            - minio
        environment:
            APP_KEY: ${APP_KEY:?err}
            APP_NAME: ${APP_NAME:-Laravel}
            APP_URL: ${APP_URL:-http://localhost:${PORT_PREFIX:-0}0080}
            INERTIA_SSR_URL: ${INERTIA_SSR_URL:-http://ssr:13714}
            LOG_STACK: ${LOG_STACK:-stderr}
            LOG_LEVEL: ${LOG_LEVEL:-error}
            LARAVEL_STORAGE_PATH: ${LARAVEL_STORAGE_PATH:-/tmp/storage}
            VIEW_COMPILED_PATH: ${VIEW_COMPILED_PATH:-/var/www/html/storage/framework/views}
            MAIL_MAILER: ${MAIL_MAILER:-log}
            MAIL_HOST: ${MAIL_HOST:-127.0.0.1}
            MAIL_PORT: ${MAIL_PORT:-2525}
            MAIL_USERNAME: ${MAIL_USERNAME:-null}
            MAIL_PASSWORD: ${MAIL_PASSWORD:-null}
            MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-null}
            MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-"hello@example.com"}
            MAIL_FROM_NAME: ${MAIL_FROM_NAME:-"${APP_NAME}"}
            DB_CONNECTION: ${DB_CONNECTION:-pgsql}
            DB_HOST: ${DB_HOST:-db}
            DB_PORT: ${DB_PORT:-5432}
            DB_DATABASE: ${DB_DATABASE:-postgres}
            DB_USERNAME: ${DB_USERNAME:-postgres}
            DB_PASSWORD: ${DB_PASSWORD:-password}
            FILESYSTEM_DISK: ${FILESYSTEM_DISK:-s3}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-minio}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-password}
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
            AWS_BUCKET: ${AWS_BUCKET:-local}
            AWS_ENDPOINT: ${AWS_ENDPOINT:-http://minio:9000}
            AWS_URL: ${AWS_URL:-http://localhost:${PORT_PREFIX:-0}9000/local}
            AWS_USE_PATH_STYLE_ENDPOINT: ${AWS_USE_PATH_STYLE_ENDPOINT:-true}
        volumes:
            - socket-upstream:/var/run/php/

    web:
        build:
            target: nginx
        depends_on:
            - laravel.test
        ports:
            - ${PORT_PREFIX:-0}0080:80
        volumes:
            - socket-upstream:/var/run/php/

    ssr:
        build:
            target: ssr
        depends_on:
            - laravel.test

    db:
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_DB: ${DB_DATABASE:-postgres}
        image: postgres:16.4
        ports:
            - ${PORT_PREFIX:-0}5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE:-postgres}", "-U", "${DB_USERNAME:-postgres}"]
            interval: 60s
            timeout: 5s
            start_period: 30s
            start_interval: 1s
            retries: 1

    minio:
        command: minio server /data/ --console-address ":9001"
        environment:
            MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-minio}
            MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-password}
        image: minio/minio
        ports:
            - ${PORT_PREFIX:-0}9000:9000
            - ${PORT_PREFIX:-0}9001:9001
        volumes:
            - minio:/data/
        healthcheck:
            test: ["CMD", "mc", "ready", "local"]
            interval: 60s
            timeout: 5s
            start_period: 30s
            start_interval: 1s
            retries: 1

volumes:
    minio:
    pgdata:
    socket-upstream:
