
---

name: ${COMPOSE_PROJECT_NAME:-}

services:

    laravel.test:
        build:
            args:
                APP_ENV: ${APP_ENV:-local}
                NODE_ENV: ${NODE_ENV:-development}
                TZ: ${APP_TIMEZONE:-UTC}
        develop:
            watch:
                - action: rebuild
                  path: ./composer.lock
                - action: rebuild
                  path: ./package-lock.json
        environment:
            APP_URL: ${APP_URL:-http://localhost:${PORT_PREFIX:-0}0080}
        ports:
            - ${PORT_PREFIX:-0}8000:8000
        volumes:
            - ./:/var/www/html/
            - socket-upstream:/var/run/php/

    web:
        build:
            args:
                APP_ENV: ${APP_ENV:-local}
                NODE_ENV: ${NODE_ENV:-development}
                TZ: ${APP_TIMEZONE:-UTC}
            target: nginx
        depends_on:
            - laravel.test
        develop:
            watch:
                - action: sync+restart
                  path: ./docker/nginx/default.conf
                  target: /etc/nginx/conf.d/default.conf
        ports:
            - ${PORT_PREFIX:-0}0080:80
        volumes:
            - ./public/:/var/www/html/public/:delegated
            - socket-upstream:/var/run/php/

volumes:
    socket-upstream:
