
---
services:
    laravel.test:
        build: .
        environment:
            APP_KEY: ${APP_KEY:?err}
            APP_NAME: ${APP_NAME:-Laravel}
            APP_URL: ${APP_URL:-http://localhost:${PORT_PREFIX:-0}0080}
            LOG_STACK: ${LOG_STACK:-stderr}
            LOG_LEVEL: ${LOG_LEVEL:-error}
            LARAVEL_STORAGE_PATH: ${LARAVEL_STORAGE_PATH:-/tmp/storage}
            VIEW_COMPILED_PATH: ${VIEW_COMPILED_PATH:-/var/www/html/storage/framework/views}
            MAIL_MAILER: ${MAIL_MAILER:-log}
            MAIL_HOST: ${MAIL_HOST:-127.0.0.1}
            MAIL_PORT: ${MAIL_PORT:-2525}
            MAIL_USERNAME: ${MAIL_USERNAME:-null}
            MAIL_PASSWORD: ${MAIL_PASSWORD:-null}
            MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-null}
            MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-"hello@example.com"}
            MAIL_FROM_NAME: ${MAIL_FROM_NAME:-"${APP_NAME}"}
        volumes:
            - socket-upstream:/var/run/php/

    web:
        build:
            target: nginx
        depends_on:
            - laravel.test
        ports:
            - ${PORT_PREFIX:-0}0080:80
        volumes:
            - socket-upstream:/var/run/php/

volumes:
    socket-upstream:
