---

version: '3'

services:

  mysql:
    image: mysql:5.7
    ports:
      - 33306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: l4r4v3l
      TZ: Asia/Tokyo
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  php:
    build: .
    ports:
      - 39000:9000
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:l4r4v3l@mysql/laravel

  nginx:
    image: nginx:1.15
    ports:
      - 30080:80
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  mysql:
    driver: local
